### ISSUE TITLE
제안서 리뷰 

### ISSUE THREAD

**Issue by MisooKim2** [haegun2/C202309-P#1]
1. 차별점은 괜찮지만, 계획된 기능이 미흡해보입니다. 좀 더 기능을 추가해보면 어떨까요? (예: 이름에 따라서, 이름의 조사를 올바르게 설정 (미수이(가) -> 미수가 등))
2. 각 기능별 입/출력이 보다 구체화될 필요가 있어보이니, 향후 구체적으로 작성하시길 바랍니다.
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by haegun2** [comment]
확장 후 진척보고서 반영 완료하여 close 처리 하였습니다~
